src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog {

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * 
     * @ORM\Column(type="text" , length="100")
     */
    private $BlogTitle;

    /**
     * 
     * @ORM\Column(type="text" , length="100")
     */
    private $Author;

    /**
     * 
     * @ORM\Column(type="text" , length="255")
     */
    private $BlogDescription;

    public function getId() {
        return $this->id;
    }

    public function setId($Id) {
        $this->id = $Id;
    }

    public function getBlogTitle() {
        return $this->BlogTitle;
    }

    public function setBlogTitle($BlogTitle) {
        $this->BlogTitle = $BlogTitle;
    }

    public function getAuthor() {
        return $this->Author;
    }

    public function setAuthor($Author) {
        $this->Author = $Author;
    }
    
    public function getBlogDescription() {
        return $this->BlogDescription;
    }

    public function setBlogDescription($BlogDescription) {
        $this->BlogDescription = $BlogDescription;
    }

}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class BlogController extends AbstractController {

    /**
     * @Route("/" , name="home")
     * @Method({"POST"})
     */
    public function home() {

        return $this->render('blog_view/AddBlog.html.twig');
        }

        /**
         * @Route("/blog/new" ,  name="new_blog")
         * @Method({"GET" , "POST"})
         */
        public function new(Request $request){
        $blog = new blog();

        $form = $this->createFormBuilder($blog)
                ->add('BlogTitle', TextType::class, array('attr' =>
                    array('class' => 'form-control')))
                ->add('Author', TextType::class, array('attr' =>
                    array('class' => 'form-control')))
                ->add('BlogDescription', TextareaType::class, array(
                    'required' => false,
                    'attr' => array('class' => 'form-control')
                ))
                ->add('save', SubmitType::class, array(
                    'label' => 'Add',
                    'attr' => array('class' => 'btn btn-dark float-right px-5 text-white mt-3')
                ))
                ->getForm();

        return $this->render('blog_view/AddBlog.html.twig', array(
                    'form' => $form->createView()
        ));
    }

    /**
     * @Route("/blog", name="blogs")
     * 
     * @Method({"GET"})
     */

    public function blog() {

        $blogs = $this->getDoctrine()->getRepository(Blog::class)->findAll();

        return $this->render('blog_view/showBlog.html.twig', array('blogs' => $blogs));
    }

    /**
     * @Route("/singleBlog/{id}" , name="singleBlog")
     */
    public function show($id) {
        $blog = $this->getDoctrine()->getRepository(Blog::class)->find($id);
        return $this->render('blog_view/singleBlog.html.twig', array('blog' => $blog));
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}IB BLOGS!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}

            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
                  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
                  crossorigin="anonymous"
                  />

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" 
                  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
                  crossorigin="anonymous"
                  />
            
            <link rel="stylesheet" href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css"/>
            
            <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" 
                  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" 
                  crossorigin="anonymous"
                  />
            
            <link rel="stylesheet" href="css/style.css" />
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}

            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
                    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
                    crossorigin="anonymous">
            </script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
                    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" 
                    crossorigin="anonymous">
            </script>

            <script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js">
            </script>
            <script src="./public/js/datatable.js"></script>
        {% endblock %}
    </head>
    <body>

        {{ include('inc/navbar.html.twig')}}

    {% block body %}{% endblock %}
</body>
</html>

templates/blog_view/AddBlog.html.twig
{% extends "base.html.twig"%}


{% block body%}
        <div class="container my-5">
            <div class="card border-none border-dark shadow">
                <div class="card-body">
                    <div class="card shadow p-3 bg-dark">
                        <h3 class="text-bold text-white">Add Blog</h3>
                        <div class="form-outline">
{#                          <input type="search" id="form1" class="form-control form-control-sm border-light" placeholder="Search Blog"#}
{#                          aria-label="Search" />#}
                        </div>
                    </div>
                    <div class="my-3">
                        {{ form_start(form) }}
                        {{ form_widget(form) }}
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
{% endblock %} 

templates/blog_view/showBlog.html.twig
{# empty Twig template #}
{% extends "base.html.twig"%}


{% block body%}
    <div class="container my-5">
        <div class="card border-none border-dark shadow">
            <div class="card-body">
                <div class="card shadow p-3 bg-dark">
                    <h3 class="text-bold text-white">ALL Blog</h3>
                </div>
                <div class="my-3">

                    <table id="blog_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th class="sorting sorting_asc" scope = "col">ID</th>
                                <th class="sorting" scope = "col">Title</th>
                                <th class="sorting" scope = "col">Author</th>
                                <th class="sorting" scope = "col">Description</th>
                                <th class="sorting" scope = "col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for blog in blogs %}
                                <tr>
                                    <th scope = "col">{{blog.id}}</th>
                                    <th scope = "col">{{blog.blogTitle}}</th>
                                    <th scope = "col">{{blog.Author}}</th>
                                    <th scope = "col">{{blog.blogDescription}}</th>
                                    <th scope = "col">
                                        <a href = "#"><i class = "fa fa-pen text-dark px-2"></i></a>
                                        <a href = "#"><i class = "fa fa-trash text-danger"></i></a>
                                        <a href="/singleBlog/{{blog.id}}"><i class = "fa fa-eye text-primary px-2"></i></a>
                                    </th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %} 

templates/blog_view/singleBlog.html.twig
{# empty Twig template #}

{% extends "base.html.twig"%}

{% block body%}

    <div class="container my-5">
        <div class="card border-none border-dark shadow">
            <div class="card-body">
                <div class="card shadow p-3 bg-dark">
                    <div class="row"> 
                        <div class="col-10">
                            <h3 class="text-bold text-white">{{blog.id}} : {{blog.blogTitle}}</h3>
                        </div>
                        <div class="col-2">
                            <a href="/blog"><i class="fa fa-arrow-left float-right mt-2 text-white"></i></a>
                        </div>
                    </div>
                </div>
                <div class="p-3">
                    <h1>Id : </h1>
                    <p class=" h5">Author : {{blog.Author}}</p>
                    <h5>{{blog.blogDescription}}</h5>            
                </div>

            </div>
        </div>
    </div>

{% endblock %}

templates/inc/navbar.html.twig
{# empty Twig template #}

<div class="header">
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img src="{{asset('images/infobeansWhite.png')}}" alt="IB_logo" class="w-50"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{path('home')}}">ADD <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{path('blogs')}}">BLOGS</a>
                </li>
            </ul>
        </div>
    </nav>
</div>